<?xml version="1.0" encoding="utf-8"?><Database Name="CRM_Test_Security" Class="DbSharedDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ffcrm-test.database.windows.net;Initial Catalog=CRM_Test_Security;Persist Security Info=True;User ID=ffcrmTest" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM_Test_SecurityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ForgotPasswordRequests" Member="ForgotPasswordRequests">
    <Type Name="ForgotPasswordRequest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RequestedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Guid" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalUsers" Member="GlobalUsers">
    <Type Name="GlobalUser">
      <Column Name="GlobalUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdminUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BrowserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BrowserVersion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateFormat" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DateFormatReports" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DisplayLanguage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguagesSpoken" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PhoneExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ProfilePicture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScreenResolution" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SignatureImage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SignatureText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="StateProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeZone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneCityNames" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TimeZoneExchange" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TimeZoneOffset" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserActivationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDeactivationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserRoles" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FreeTrialRequests" Member="FreeTrialRequests">
    <Type Name="FreeTrialRequest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EmailMessageId" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Guid" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RequestedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VerifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Converted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConvertedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalSubscribers" Member="GlobalSubscribers">
    <Type Name="GlobalSubscriber">
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Billable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FreeTrial" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>