<?xml version="1.0" encoding="utf-8"?><Database Name="CRM_Test_Shared" Class="DbSharedDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ffcrm-test.database.windows.net;Initial Catalog=CRM_Test_Shared;Persist Security Info=True;User ID=ffcrmTest" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM_Test_SharedConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activities" Member="Activities">
    <Type Name="Activity">
      <Column Name="ActivityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AdminActiveOveride" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminActiveOverideDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivityType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusyFree" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CalendarEventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Campaigns" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CompanySubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Competitors" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompletionPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactIds" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactNames" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ConversionActivityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConversionCreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConversionUpdatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedUserLocation" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DealIds" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DealNames" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DealTypes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EventSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EventTimeZone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ExchangeAppointmentId" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ExchangeAppointmentItemId" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ExchangeSyncId" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="ExchangeSyncLastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GoogleSyncId" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="GoogleSyncLastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsAllDay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRecurring" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoteContent" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="NoteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OriginSystem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PublicPrivate" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Priority" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Reminder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReminderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReminderIncrement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReminderIncrementType" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ReminderMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReminderType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ReoccurNumberOfTimes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReoccurrenceIncrement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReoccurrenceIncrementType" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ReoccurrenceParentActivityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SalesPurpose" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalesStage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SavedAsActivity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SourceDataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SourceDataCenterCalendarEventId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceDataCenterNoteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceDataCenterTaskId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceSubscriberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SyncType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TaskId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaskName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserLocation" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserTimeZone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UtcOffset" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebAppErrors" Member="WebAppErrors">
    <Type Name="WebAppError">
      <Column Name="WebAppErrorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErrorCallStack" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="PageCalledFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoutineName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ActivititesMembers" Member="ActivititesMembers">
    <Type Name="ActivititesMember">
      <Column Name="ActivityMemberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivitiesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttendeeType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ContactSubscriberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InviteAccepted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InviteType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserIdGlobal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Airports" Member="Airports">
    <Type Name="Airport">
      <Column Name="AirportId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AirportType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="AirportName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Continent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ElevationFeet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GpsCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="IataCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="IdentifierCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="IsoRegion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LocalCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Municipality" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ScheduledService" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UrlHome" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UrlWikipedia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AllActivities" Member="AllActivities">
    <Type Name="AllActivity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BusyFree" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CalendarEventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Campaigns" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyIds" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyIdGlobals" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyNames" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Competitors" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompletionPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContactIds" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Contacts" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedGlobalUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DealIds" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DealNames" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DealTypes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EventSubject" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EventTimeZone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="IsAllDay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRecurring" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoteContent" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="NoteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OriginSystem" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PublicPrivate" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Priority" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SalesStage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SourceDataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SourceDataCenterCalendarEventId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceSubscriberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TaskId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaskName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserTimeZone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UtcOffset" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Campaigns" Member="Campaigns">
    <Type Name="Campaign">
      <Column Name="CampaignId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CampaignOwnerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CampaignOwnerUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CampaignName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CampaignNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CampaignStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CampaignType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdateUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CountryDialingCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Country_ISO_Code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LocalCurrencyCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegionContinent" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DateFormat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Timezone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currencies" Member="Currencies">
    <Type Name="Currency">
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyFormat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CurrencyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="SubUnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubUnitRatio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CurrencyExchangeRates" Member="CurrencyExchangeRates">
    <Type Name="CurrencyExchangeRate">
      <Column Name="CurrencyExchangeRateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="ExchangeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExchangeRatesLog" Member="ExchangeRatesLogs">
    <Type Name="ExchangeRatesLog">
      <Column Name="ExchangeRatesLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ElapsedTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RecordsAdded" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecordsDeleted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecordsExported" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecordsUpdated" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReturnMessage" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RoutineName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RoutineType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Success" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ExchangeServerTimezones" Member="ExchangeServerTimezones">
    <Type Name="ExchangeServerTimezone">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExchangeServerTimeZone" Member="ExchangeServerTimeZone1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalCompanies" Member="GlobalCompanies">
    <Type Name="GlobalCompany">
      <Column Name="GlobalCompanyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdminOverideActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdminOverideActiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Campaigns" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Claimed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ClaimedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClaimedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyOwnerUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyOwnerUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanySegmentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CompanyTypes" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreditLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Division" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstShipmentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GlobalCompanyOwnerGlobalUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCompanyOwnerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Incoterms" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Industry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsCustomer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastCreditUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastShipmentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LinkedUserEmails" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LinkedUserNames" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NextActivityDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberOfEmployees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PrimaryContactId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalesTeam" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SourceDataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SourceDataCenterCompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateProvince" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConversionAccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConversionLeadId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConversionType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataCenterConversionAddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataCenterConversionUpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GlobalCompanyOwnerGlobalUserName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalCompanyAccessRequest" Member="GlobalCompanyAccessRequests">
    <Type Name="GlobalCompanyAccessRequest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Guid" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RequestedGlobalUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyOwnerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Accepted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AcceptedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalDeals" Member="GlobalDeals">
    <Type Name="GlobalDeal">
      <Column Name="DealIdGlobal" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DealId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Campaign" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CBMs" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Commodities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Competitors" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ContractEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContractStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateLost" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateProposalDue" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateWon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DealDescription" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DealName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DealNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealOwnerUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealOwnerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DealType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DecisionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DistrictCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealSource" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EstimatedStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Industry" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Kgs" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Lbs" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NextActivityDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrimaryContactId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryContactName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Profit" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProfitPercentage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ProfitUSD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ReasonLost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReasonWon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReasonWonLost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Revenue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RevenueUSD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SalesStageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalesStageName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SalesTeam" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Services" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SourceDataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SourceDataCenterDealId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceSubscriberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpotDeal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEUs" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Tonnes" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WonExchangeRate" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalLocations" Member="GlobalLocations">
    <Type Name="GlobalLocation">
      <Column Name="GlobalLocationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Airport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IataCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="InlandPort" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MultiModal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RoadTerminal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RailTerminal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SeaPort" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UnlocoCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UpdateUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalSubscribers" Member="GlobalSubscribers">
    <Type Name="GlobalSubscriber">
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalUserActivationsDeactivations" Member="GlobalUserActivationsDeactivations">
    <Type Name="GlobalUserActivationsDeactivation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivatedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivatedByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActivatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeactivatedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeactivatedByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeactivatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalUsers" Member="GlobalUsers">
    <Type Name="GlobalUser">
      <Column Name="GlobalUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BrowserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BrowserVersion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateFormat" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DateFormatReports" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DisplayLanguage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguagesSpoken" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PhoneExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ProfilePicture" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScreenResolution" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SignatureImage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SignatureText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="StateProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeZone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneCityNames" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TimeZoneExchange" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TimeZoneOffset" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserActivationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDeactivationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserRoles" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IataAirports" Member="IataAirports">
    <Type Name="IataAirport">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ident" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="latitude_deg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="longitude_deg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elevation_ft" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="continent" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="iso_country" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="iso_region" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="municipality" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="scheduled_service" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="gps_code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="iata_code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="local_code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="home_link" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="wikipedia_link" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keywords" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Incoterms" Member="Incoterms">
    <Type Name="Incoterm">
      <Column Name="IncotermId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Incoterm" Member="Incoterm1" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="CarrierLoadOnTruck" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ExportCustomsDeclaration" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CarriageToPortOfExport" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UnloadTruckInPortOfExport" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LoadingChargesInPortOfExport" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CarriageToPortOfImport" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UnloadingChargesInPortOfImport" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LoadingOnTruckInPortOfIimport" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CarriageToPlaceOfDestination" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Insurance" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ImportCustomsClearance" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ImportTaxes" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LanguagePhrases" Member="LanguagePhrases">
    <Type Name="LanguagePhrase">
      <Column Name="LanguagePhraseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedByUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguagePhrase" Member="LanguagePhrase1" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Languages" Member="Languages">
    <Type Name="Language">
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LanguageTranslations" Member="LanguageTranslations">
    <Type Name="LanguageTranslation">
      <Column Name="LanguageTranslationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguageCode" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="LanguageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LanguagePhrase" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Translation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VerifiedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VerifiedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LinkActivityToDeal" Member="LinkActivityToDeals">
    <Type Name="LinkActivityToDeal">
      <Column Name="LinkActivityToDealId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DealName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DealSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LinkCountryRegion" Member="LinkCountryRegions">
    <Type Name="LinkCountryRegion">
      <Column Name="LinkCountryRegionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LinkGlobalCompanyGlobalUser" Member="LinkGlobalCompanyGlobalUsers">
    <Type Name="LinkGlobalCompanyGlobalUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GlobalCompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCompanyName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="GlobalUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GlobalUserName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CompanySubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalesTeamRole" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LinkGlobalDealGlobalUser" Member="LinkGlobalDealGlobalUsers">
    <Type Name="LinkGlobalDealGlobalUser">
      <Column Name="LinkGloablDealGlobalUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DealSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GlobalDealId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GlobalDealName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="GlobalUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GlobalUserName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="LinkType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LinkGlobalSuscriberToSubscriber" Member="LinkGlobalSuscriberToSubscribers">
    <Type Name="LinkGlobalSuscriberToSubscriber">
      <Column Name="LinkGlobalSubscriberToSubscriberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GlobalSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LinkedSubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OutlookCategoryColors" Member="OutlookCategoryColors">
    <Type Name="OutlookCategoryColor">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HexColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RGB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SalesTeamRoles" Member="SalesTeamRoles">
    <Type Name="SalesTeamRole">
      <Column Name="SalesTeamRoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalesTeamRole" Member="SalesTeamRole1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TimeZones" Member="TimeZones">
    <Type Name="TimeZone">
      <Column Name="TimeZoneId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityNames" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UtcOffset" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EnumTimeZoneID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimeZonesDaylightSavings" Member="TimeZonesDaylightSavings">
    <Type Name="TimeZonesDaylightSaving">
      <Column Name="TimeZonesDaylightSavingsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DstStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DstEndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeZoneFullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TimeZoneYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UtcOffset" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UnlocoCodes" Member="UnlocoCodes">
    <Type Name="UnlocoCode">
      <Column Name="UnlocoCodeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UnlocoCode" Member="UnlocoCode1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Airport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BorderCrossing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Coordinates" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedById" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FixedTransport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FunctionNotKnown" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IataCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="InlandPort" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LocationDate" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="LocationFunction" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LocationNameWithDiacriticals" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Multimodal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostalExchangeOffice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RailTerminal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RoadTerminal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Seaport" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubdivisionCode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchesPortCode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PortName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnlocoPorts" Member="UnlocoPorts">
    <Type Name="UnlocoPort">
      <Column Name="UnlocoPortId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Coordinates" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CountryCode" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PortName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UnlocoCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsCustomer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserRole" Member="UserRole1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Regions" Member="Regions">
    <Type Name="Region">
      <Column Name="RegionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedUserIdGlobal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RegionManagerUserIdGlobal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserIdGlobal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>